title: 2hog trainings
email: hello@2hog.codes
description: >- # ignore newlines until "baseurl:"
  This is the website of all 2hog training material.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  2hog

# Build settings
markdown: kramdown

collections:
  presentations:
    output: true

defaults:
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
      permalink: "/:title/"

plugins:
  - jekyll-redirect-from
