apiVersion: batch/v1
kind: Job
metadata:
  name: steve
spec:
  template:
    spec:
      containers:
        - name: steve
          image: "ubuntu:18.04"
          command: ["echo",  "Hi, I am a long running process computing stuff."]
      restartPolicy: Never
