apiVersion: batch/v1
kind: Job
metadata:
  name: deadline-job
spec:
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
        - name: deadline-job
          image: "ubuntu:18.04"
          command: ["sleep",  "2", "&&", "exit", "1"]
      restartPolicy: Never
